import type { Metadata } from "next";
import "./globals.css";

// 使用系统字体替代 Google Fonts，避免网络连接问题
const fontVariables = {
  "--font-geist-sans":
    "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
  "--font-geist-mono":
    "'SF Mono', 'Monaco', 'Inconsolata', 'Roboto Mono', monospace",
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased"
        style={fontVariables as React.CSSProperties}
      >
        {children}
      </body>
    </html>
  );
}
